### ISSUE TITLE
Training stuck in the single episode success

### ISSUE THREAD

**Issue by GEEKZE97** [Levinin/webots_epuck_ddpg#1]
It seems that the training procedure got stuck in finishing the first episode. can you help to check it?
![image](https://github.com/Levinin/webots_epuck_ddpg/assets/34502024/0cc1d721-67ec-4f0a-993c-cf891f5c8efd)
I printed the message from the supervisor side. It will never output 'success'
![image](https://github.com/Levinin/webots_epuck_ddpg/assets/34502024/fa787b98-ac52-4b16-ba41-745ae99b5334)

**Comment by GEEKZE97** [comment]
By the way, I directly run the code on Webots rather than Pycharm. Do I have to run it on Pycharm?

**Comment by Levinin** [comment]
You can just run it in Webots directly. There must an issue with your setup because it definitely works. In particular, check you are using Webots 2023b. I'm not planning updates for any changes in newer versions.
